---
title: "test"
author: "Aleksandra Dacko"
date: "1/19/2023"
output: html_document
---

```{r setup, include=FALSE}
#library(devtools)
#devtools::install_github("emmekeaarts/mHMMbayes@continuous-emiss")
library(mHMMbayes)
data<-readRDS("simulated_data/three_state_design.rds")

```

```{r}
obs_sc=3
dwel_sc=3
sim_no=20
n_t=500
m=3

mhmmdt<-data[[obs_sc]][[dwel_sc]][[sim_no]][["observations"]]
#---set seed--------------------------------------------------------------------
set.seed(123)
#---set starting values for emission and gamma----------------------------------

emiss_distr <- list(matrix(c(12.5,10,
                             35, 10,
                             62.5,10), nrow = m, byrow = TRUE))
gamma   <- matrix(c(0.95, 0.025,0.025,
                          0.025, 0.95, 0.025,
                          0.025, 0.025, 0.95), ncol = m, byrow = TRUE)

#---Specify hyper-prior for the continuous emission distribution----------------
hyp_pr <- list(
  emiss_mu0 = list(matrix(c(12.5,35,62.5), nrow = 1)),
  emiss_K0  = list(40),
  emiss_nu  = list(1),
  emiss_V   = list(rep(1, m)),
  emiss_a0  = list(rep(1, m)),
  emiss_b0  = list(rep(1, m)))


#model fitting
out_st3<- mHMM_cont(s_data = mhmmdt,
                                gen = list(m = 3, n_dep = 1),
                                start_val = c(list(gamma), emiss_distr),
                                emiss_hyp_prior = hyp_pr,
                                mcmc = list(J = 100, burn_in =20))
#state decoding
state_decoding<-vit_mHMM_cont(s_data=mhmmdt,object =out_st3)

pdf("Plots/test.pdf")
for(sub in 1:3){
  sub_st_class<-data.frame(time=1:n_t,obs=data[[obs_sc]][[dwel_sc]][[sim_no]][["observations"]][(sub * n_t - n_t+1):(sub * n_t ) ,2],st=data[[obs_sc]][[dwel_sc]][[sim_no]][["states"]][(sub * n_t - n_t+1):(sub * n_t ) ,2])
  sub_st_class$st<-as.factor(sub_st_class$st)
  state_decoding_ss<-data.frame(time=1:n_t, st=state_decoding[,sub])
  
  par(mar = c(4.3, 6.6, 2.1, 1.1))
  plot(x = 1, xlim = c(0,nrow(sub_st_class)), ylim = c(-40,90), type = "n", las = 1, xlab = "Time in minutes", xaxt = "n", yaxt = "n", ylab = "")
  axis(2, at = -20, tick = FALSE, labels = c("True class"), las = 1)
  axis(2, at = -30, tick = FALSE, labels = c("MEDHMM"), las = 1)
  axis(2, at = -40, tick = FALSE, labels = c("MHMM"), las = 1)
  
  axis(1, at = seq(0,nrow(sub_st_class),10), tick = TRUE, las = 1, labels = FALSE)
  axis(1, at = seq(0,nrow(sub_st_class),10), tick = FALSE, las = 1) 
  abline(v = seq(0,nrow(sub_st_class),10), col = "gray85")
  lines(x=sub_st_class$time,y=sub_st_class$obs)
  coll<-c("red","blue","green")
  for(i in 1:3){
  points(x = sub_st_class$time[sub_st_class$st == i],
         y = rep(-20, sum(sub_st_class$st == i)),
         pch = "|", col =coll[i] )
    }
#for(i in 1:3){
#  points(x = sub_st_class$time[sub_st_class$st == i],
#         y = rep(-30, sum(sub_st_class$st == i)),
#         pch = "|", col =coll[i] )
#}
  for(i in 1:3){
    points(x = state_decoding_ss$time[state_decoding_ss$st == i],
         y = rep(-40, sum(state_decoding_ss$st == i)),
         pch = "|", col =coll[i] )
}
  title(main=expression("State decodings"))

}
dev.off()

```

